spring:
  application:
    name: Arquitetura Spring
  jpa:
    show-sql: true
  main:
    lazy-initialization: false

app:
  montadora:
    motor-padrao: 220
  config:
    variavel: VALOR DA VARIÁVEL X
    valor1: 600
